#include<stdio.h>
int a, b;
 void print(){
    printf("%d %d",a,b);
 }

 int fun1(){
    int a,c;
    a = 0;
    b = 1;
    c = 2;
    return c;
 }

 void fun2(){
    int b;
    a = 3;
    b = 4;
    print();
 }

int main(){
    a = fun1();
    fun2();
}

// First globally:
//  global a=0, global b=0 taken by the compiler

// Second it enters main( ):
// global a = output generated by fun1( ), global b = 0

// Third it enters fun1( ):
//  global a = 0, global b = 1,  local a = 0, local c = 2   (AS IT IS NOW DEALING WITH LOCAL VARIABLES)

// meanwhile in main( ):
//  global a =2

// fourth it enters fun2( ):
// global a = 3, global b = 1, local b = 4 (AS ONLY "b" IS DEFINED LOCALLY)

// Finally print( ):
//  Static prints global 'a' and 'b'. (a =3, b=1)
//  Dynamic prints the values it finds in immediate function from where print( ) is called (a=3, b =4)